/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#00685f',
        'primary-container': '#008378',
        'on-primary': '#ffffff',
        'on-primary-container': '#f4fffc',
        'primary-fixed': '#89f5e7',
        'primary-fixed-dim': '#6bd8cb',
        'on-primary-fixed': '#00201d',
        'on-primary-fixed-variant': '#005049',
        'inverse-primary': '#6bd8cb',
        'secondary': '#565e74',
        'secondary-container': '#dae2fd',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#5c647a',
        'secondary-fixed': '#dae2fd',
        'secondary-fixed-dim': '#bec6e0',
        'on-secondary-fixed': '#131b2e',
        'on-secondary-fixed-variant': '#3f465c',
        'tertiary': '#924628',
        'tertiary-container': '#b05e3d',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#ffdbce',
        'tertiary-fixed-dim': '#ffb59a',
        'on-tertiary-fixed': '#370e00',
        'on-tertiary-fixed-variant': '#773215',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'surface': '#f5faf8',
        'surface-dim': '#d6dbd9',
        'surface-bright': '#f5faf8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f5f2',
        'surface-container': '#eaefed',
        'surface-container-high': '#e4e9e7',
        'surface-container-highest': '#dee4e1',
        'surface-variant': '#dee4e1',
        'surface-tint': '#006a61',
        'on-surface': '#171d1c',
        'on-surface-variant': '#3d4947',
        'inverse-surface': '#2c3130',
        'inverse-on-surface': '#edf2f0',
        'outline': '#6d7a77',
        'outline-variant': '#bcc9c6',
        'background': '#f5faf8',
        'on-background': '#171d1c',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        '2xl': '48px',
        'gutter': '24px',
      },
      borderRadius: {
        'sm': '0.125rem',
        DEFAULT: '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      boxShadow: {
        'card': '0px 4px 12px rgba(15, 23, 42, 0.04)',
        'card-hover': '0px 8px 24px rgba(15, 23, 42, 0.08)',
        'popover': '0px 12px 24px rgba(15, 23, 42, 0.1)',
        'mobile-nav': '0 -4px 12px rgba(15, 23, 42, 0.04)',
      },
      fontSize: {
        'label-caps': ['11px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'small': ['12px', { lineHeight: '1.4', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', letterSpacing: '0em', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'h3': ['18px', { lineHeight: '1.4', letterSpacing: '0em', fontWeight: '600' }],
        'h2': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h1': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
